### ISSUE TITLE
Working example of jsr107 cache statistics

### ISSUE THREAD

**Issue by kliakos** [ehcache/ehcache3-samples#25]
I really can't find a way to make the jsr107 statistics work. Can we have a working example in the sample?

**Comment by henri-tremblay** [comment]
Can you please be clearer? What is not working? Also, asking such question on the mailing list would be a better idea.

Normally, just activate the statistics is enough to see them in JMX. You have an example in the samples in the `ehcache.xml`.

```xml
  <service>
    <jsr107:defaults enable-management="false" enable-statistics="true"/>
  </service>
```

**Comment by kliakos** [comment]
I would like to see an example where cacheHits and cacheMisses are outputted to the console. I can see how the statistics are enabled, however I also want to see how they are accessed. A couple of examples I tried both failed with an exception.

If you think this feature request for the examples repor is too naive, you can close the issue.

**Comment by henri-tremblay** [comment]
Right. In fact the code was existing in the fullstack example but was then collaborate to the dropwizard metrics project. So you can find an example with the [JCacheGaugeSet](https://github.com/dropwizard/metrics/blob/4.1-development/metrics-jcache/src/main/java/com/codahale/metrics/jcache/JCacheGaugeSet.java).

**Comment by kliakos** [comment]
I will post this code snippet here in case anyone finds it helpful. I can do a PR if you want in order to embed this in the examples.

```java
final MBeanServer beanServer = ManagementFactory.getPlatformMBeanServer();

final Set<ObjectInstance> cacheBeans = beanServer.queryMBeans(ObjectName.getInstance("javax.cache:type=CacheStatistics,CacheManager=*,Cache=*"), null);

for ( ObjectInstance cacheBean : cacheBeans ) {
	final CacheStatisticsMXBean cacheStatisticsMXBean = MBeanServerInvocationHandler.newProxyInstance(beanServer, cacheBean.getObjectName(), CacheStatisticsMXBean.class, false);

	System.out.println("Gets: " + cacheStatisticsMXBean.getCacheGets());
	System.out.println("Hits: " + cacheStatisticsMXBean.getCacheHits());
	System.out.println("Misses: " + cacheStatisticsMXBean.getCacheMisses());
	System.out.println("Removals: " + cacheStatisticsMXBean.getCacheRemovals());
	System.out.println("Evictions: " + cacheStatisticsMXBean.getCacheEvictions());
	System.out.println("Avg Get Time: " + cacheStatisticsMXBean.getAverageGetTime());
	System.out.println("Avg Put Time: " + cacheStatisticsMXBean.getAveragePutTime());
	System.out.println("Avg Remove Time: " + cacheStatisticsMXBean.getAverageRemoveTime());
}
