### ISSUE TITLE
Exception while starting server

### ISSUE THREAD

**Issue by srinuydlp** [ehcache/ehcache3-samples#31]
**Fatal Terracotta startup exception:

 org.terracotta.config.TCConfigurationSetupException: Couldn't parse configurati
on file, there are 2 error(s).
 [1] Line 3, column 13: cvc-complex-type.2.4.a: Invalid content was found starti
ng with element 'services'. One of '{"http://www.terracotta.org/config":plugins,
 "http://www.terracotta.org/config":tc-properties, "http://www.terracotta.org/co
nfig":failover-priority, "http://www.terracotta.org/config":servers}' is expecte
d.
 [2] Line 13, column 13: cvc-complex-type.2.4.a: Invalid content was found start
ing with element 'data'. One of '{"http://www.terracotta.org/config":logs, "http
://www.terracotta.org/config":tsa-group-port}' is expected.

Server startup failed.
2018-05-25 16:29:04,430 [main] INFO com.tc.properties.TCPropertiesImpl - The pro
perty "l2.nha.autoRestart" was read before initialization completed. "l2.nha.aut
oRestart" = true
2018-05-25 16:29:04,434 [main] INFO com.tc.server.TCServerMain - ExitState : Cal
lbackOnExitState[Throwable: class com.tc.config.schema.setup.ConfigurationSetupE
xception; RestartNeeded: false]; AutoRestart: true**

**Comment by henri-tremblay** [comment]
You are right. The samples are out of date.

**Comment by srinuydlp** [comment]
Can you please upload latest. I need some samples on ehchache cluster.

**Comment by henri-tremblay** [comment]
Just did. The PR is out: #32

**Comment by srinuydlp** [comment]
Thanks I will check if I face any issues please help thanks allot

**Comment by henri-tremblay** [comment]
Please use the mailing list for such question since it's not a bug anymore. You basically just do. But the list content needs to be serializable (and you will get a warning about the List not being serializable but it's just a warning)

**Comment by srinuydlp** [comment]
I am getting exception not warning. To which mail I have to send ?

**Comment by henri-tremblay** [comment]
https://groups.google.com/forum/#!forum/ehcache-users
